//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPDCtrl.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPDCtrl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ack_Window_Clear {
            get {
                return ResourceManager.GetString("Ack_Window_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangePasswordDialog_ChangePassword {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangePasswordDialog_CurrentPassword {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Password did not match. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangePasswordDialog_CurrentPasswordMismatch {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_CurrentPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangePasswordDialog_NewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password Updated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangePasswordDialog_PasswordUpdated {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_Connected {
            get {
                return ResourceManager.GetString("ConnectionStatus_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. (ConnectFail_Timeout) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_ConnectFail_Timeout {
            get {
                return ResourceManager.GetString("ConnectionStatus_ConnectFail_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_Connecting {
            get {
                return ResourceManager.GetString("ConnectionStatus_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionStatus_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to connect to specified MPD server. Please check your connection settings or MPD server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_ConnectionErrorDetails {
            get {
                return ResourceManager.GetString("ConnectionStatus_ConnectionErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection has been terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_Disconnected {
            get {
                return ResourceManager.GetString("ConnectionStatus_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_DisconnectedByHost {
            get {
                return ResourceManager.GetString("ConnectionStatus_DisconnectedByHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_DisconnectedByUser {
            get {
                return ResourceManager.GetString("ConnectionStatus_DisconnectedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnecting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_Disconnecting {
            get {
                return ResourceManager.GetString("ConnectionStatus_Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_NeverConnected {
            get {
                return ResourceManager.GetString("ConnectionStatus_NeverConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_SendFail_NotConnected {
            get {
                return ResourceManager.GetString("ConnectionStatus_SendFail_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_SendFail_Timeout {
            get {
                return ResourceManager.GetString("ConnectionStatus_SendFail_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Debug_Window_Clear {
            get {
                return ResourceManager.GetString("Debug_Window_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Debug_Window_Close {
            get {
                return ResourceManager.GetString("Debug_Window_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Developer Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeveloperMode {
            get {
                return ResourceManager.GetString("DeveloperMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close (Esc) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_CancelClose {
            get {
                return ResourceManager.GetString("Dialog_CancelClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comfirmation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Comfirmation {
            get {
                return ResourceManager.GetString("Dialog_Comfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Information {
            get {
                return ResourceManager.GetString("Dialog_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Input {
            get {
                return ResourceManager.GetString("Dialog_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Playlist Name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_NewPlaylistName {
            get {
                return ResourceManager.GetString("Dialog_NewPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playlist name already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_PlaylistNameAlreadyExists {
            get {
                return ResourceManager.GetString("Dialog_PlaylistNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_PlaylistSelect_NewPlaylistName {
            get {
                return ResourceManager.GetString("Dialog_PlaylistSelect_NewPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Selected to に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_PlaylistSelect_SaveSelectedTo {
            get {
                return ResourceManager.GetString("Dialog_PlaylistSelect_SaveSelectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_PlaylistSelect_SelectPlaylist {
            get {
                return ResourceManager.GetString("Dialog_PlaylistSelect_SelectPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove selected playlist? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_RemovePlaylistQ {
            get {
                return ResourceManager.GetString("Dialog_RemovePlaylistQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear Filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterClear {
            get {
                return ResourceManager.GetString("FilterClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Host に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Connection Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Init_NewConnectionSetting {
            get {
                return ResourceManager.GetString("Init_NewConnectionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copyright (c) 2020 torum
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permiss [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The MIT License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LicenseTitle {
            get {
                return ResourceManager.GetString("LicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add (Enter) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocalfileItemContextMenu_Add {
            get {
                return ResourceManager.GetString("LocalfileItemContextMenu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocalfileListviewColumnHeader_FileName {
            get {
                return ResourceManager.GetString("LocalfileListviewColumnHeader_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocalfileListviewTabitemHeader_LocalFiles {
            get {
                return ResourceManager.GetString("LocalfileListviewTabitemHeader_LocalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuTreeItem_Browse {
            get {
                return ResourceManager.GetString("MenuTreeItem_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playlists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuTreeItem_Playlists {
            get {
                return ResourceManager.GetString("MenuTreeItem_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Queue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuTreeItem_Queue {
            get {
                return ResourceManager.GetString("MenuTreeItem_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuTreeItem_Search {
            get {
                return ResourceManager.GetString("MenuTreeItem_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command Response に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MPD_CommandError {
            get {
                return ResourceManager.GetString("MPD_CommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status Notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MPD_StatusError {
            get {
                return ResourceManager.GetString("MPD_StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_BackButton {
            get {
                return ResourceManager.GetString("Playback_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_NextButton {
            get {
                return ResourceManager.GetString("Playback_NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play/Pause に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_PlayPauseButton {
            get {
                return ResourceManager.GetString("Playback_PlayPauseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seek に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_SliderSeek {
            get {
                return ResourceManager.GetString("Playback_SliderSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_SliderVolume {
            get {
                return ResourceManager.GetString("Playback_SliderVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaybackOptions_Consume {
            get {
                return ResourceManager.GetString("PlaybackOptions_Consume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaybackOptions_Repeat {
            get {
                return ResourceManager.GetString("PlaybackOptions_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shuffle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaybackOptions_Shuffle {
            get {
                return ResourceManager.GetString("PlaybackOptions_Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaybackOptions_Single {
            get {
                return ResourceManager.GetString("PlaybackOptions_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear Queue and Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistItemContextMenu_ClearAndLoad {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_ClearAndLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load (Enter) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistItemContextMenu_Load {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistItemContextMenu_Remove {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistItemContextMenu_Rename {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Playlists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistListviewTabitemHeader_Playlists {
            get {
                return ResourceManager.GetString("PlaylistListviewTabitemHeader_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playlists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistsListviewColumnHeader_Playlists {
            get {
                return ResourceManager.GetString("PlaylistsListviewColumnHeader_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistSongsContextMenu_Clear {
            get {
                return ResourceManager.GetString("PlaylistSongsContextMenu_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistSongsContextMenu_Playlist {
            get {
                return ResourceManager.GetString("PlaylistSongsContextMenu_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove From Playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistSongsContextMenu_Remove {
            get {
                return ResourceManager.GetString("PlaylistSongsContextMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Clear Playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Popup_ConfirmClearPlaylist {
            get {
                return ResourceManager.GetString("Popup_ConfirmClearPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear Playlist? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Popup_ConfirmClearPlaylistQuestion {
            get {
                return ResourceManager.GetString("Popup_ConfirmClearPlaylistQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Clear Queue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Popup_ConfirmClearQueue {
            get {
                return ResourceManager.GetString("Popup_ConfirmClearQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear Queue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Popup_ConfirmClearQueueQuestion {
            get {
                return ResourceManager.GetString("Popup_ConfirmClearQueueQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload Playlist? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Popup_ConfirmReloadPlaylistQuestion {
            get {
                return ResourceManager.GetString("Popup_ConfirmReloadPlaylistQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Remove Playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Popup_ConfirmRemovePlaylist {
            get {
                return ResourceManager.GetString("Popup_ConfirmRemovePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Selected Playlist? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Popup_ConfirmRemovePlaylistQuestion {
            get {
                return ResourceManager.GetString("Popup_ConfirmRemovePlaylistQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Remove Selected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Popup_ConfirmRemoveSelected {
            get {
                return ResourceManager.GetString("Popup_ConfirmRemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Selected? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Popup_ConfirmRemoveSelectedQuestion {
            get {
                return ResourceManager.GetString("Popup_ConfirmRemoveSelectedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input New Playlist Name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Popup_InputNewPlaylistName {
            get {
                return ResourceManager.GetString("Popup_InputNewPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple Deletion Not Supported に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Popup_MultipleDeletionNotSupported {
            get {
                return ResourceManager.GetString("Popup_MultipleDeletionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Suppoted By MPD Protocol に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Popup_NotSuppotedByMPDProtocol {
            get {
                return ResourceManager.GetString("Popup_NotSuppotedByMPDProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Popup_OK {
            get {
                return ResourceManager.GetString("Popup_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playlist Changed Nortification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Popup_PlaylistChangedNortification {
            get {
                return ResourceManager.GetString("Popup_PlaylistChangedNortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Queue As に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Popup_SaveQueueAs {
            get {
                return ResourceManager.GetString("Popup_SaveQueueAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Selected As に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Popup_SaveSelectedAs {
            get {
                return ResourceManager.GetString("Popup_SaveSelectedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Selected To に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Popup_SaveSelectedTo {
            get {
                return ResourceManager.GetString("Popup_SaveSelectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Playlist: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Popup_SelectPlaylist {
            get {
                return ResourceManager.GetString("Popup_SelectPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App Privacy Policy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MPDCtrl allows you to access your music player via specified IP address with optional user credentials. None of the data is transmitted anywhere besides your specified music player and your settings are stored on your device only. Optional user credentials are encrypted with a platform provided shceme. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrivacyPolicyText {
            get {
                return ResourceManager.GetString("PrivacyPolicyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profiles に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_Move {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Down (Ctrl+D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_MoveDown {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Up (Ctrl+U) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_MoveUp {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Queue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_Queue {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_QueueClear {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_QueueClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save As に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_QueueSaveAsPlaylist {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_QueueSaveAsPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove (Ctrl+Delete) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_Remove {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Selected As に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_SaveSelectedAs {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_SaveSelectedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Selected To... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_SaveSelectedTo {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_SaveSelectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jump to Current Song (Ctrl+J) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_ScrollIntoNowPlaying {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_ScrollIntoNowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected Items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_SelectedItems {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_SelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Album に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueListviewColumnHeader_Album {
            get {
                return ResourceManager.GetString("QueueListviewColumnHeader_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueListviewColumnHeader_Artist {
            get {
                return ResourceManager.GetString("QueueListviewColumnHeader_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genre に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueListviewColumnHeader_Genre {
            get {
                return ResourceManager.GetString("QueueListviewColumnHeader_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last Modified に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueListviewColumnHeader_LastModified {
            get {
                return ResourceManager.GetString("QueueListviewColumnHeader_LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueListviewColumnHeader_Position {
            get {
                return ResourceManager.GetString("QueueListviewColumnHeader_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueListviewColumnHeader_Time {
            get {
                return ResourceManager.GetString("QueueListviewColumnHeader_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueListviewColumnHeader_Title {
            get {
                return ResourceManager.GetString("QueueListviewColumnHeader_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search (Ctrl+F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search_ToolTip {
            get {
                return ResourceManager.GetString("Search_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid address format. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ErrorHostInvalidAddressFormat {
            get {
                return ResourceManager.GetString("Settings_ErrorHostInvalidAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Host address is required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ErrorHostMustBeSpecified {
            get {
                return ResourceManager.GetString("Settings_ErrorHostMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid port number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ErrorInvalidPortNaN {
            get {
                return ResourceManager.GetString("Settings_ErrorInvalidPortNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port number is required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ErrorPortMustBeSpecified {
            get {
                return ResourceManager.GetString("Settings_ErrorPortMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto scroll to current song. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_AutoScrollToNowPlaying {
            get {
                return ResourceManager.GetString("Settings_Opts_AutoScrollToNowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable AlbumArt. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_EnableAlbumArt {
            get {
                return ResourceManager.GetString("Settings_Opts_EnableAlbumArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MPD Database に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_MPDDatabase {
            get {
                return ResourceManager.GetString("Settings_Opts_MPDDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_Options {
            get {
                return ResourceManager.GetString("Settings_Opts_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save log file (MPDCtrl__errors.txt) to desktop when an unexpected error occured. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_SaveLog {
            get {
                return ResourceManager.GetString("Settings_Opts_SaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable debug widow. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_ShowDebugWidow {
            get {
                return ResourceManager.GetString("Settings_Opts_ShowDebugWidow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Themes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_Themes {
            get {
                return ResourceManager.GetString("Settings_Opts_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_Themes_Dark {
            get {
                return ResourceManager.GetString("Settings_Opts_Themes_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_Themes_Light {
            get {
                return ResourceManager.GetString("Settings_Opts_Themes_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update MPD database on startup. (It may take a while to update) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_UpdateDatabaseOnStartup {
            get {
                return ResourceManager.GetString("Settings_Opts_UpdateDatabaseOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use &quot;readpicture&quot; command instead of &quot;albumart&quot;. (applicable when MPD protocol version is 0.22.0 or up) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_UseReadPicture {
            get {
                return ResourceManager.GetString("Settings_Opts_UseReadPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile deleted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ProfileDeleted {
            get {
                return ResourceManager.GetString("Settings_ProfileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ProfileSaved {
            get {
                return ResourceManager.GetString("Settings_ProfileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile updated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ProfileUpdated {
            get {
                return ResourceManager.GetString("Settings_ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings (Ctrl+S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ToolTip {
            get {
                return ResourceManager.GetString("Settings_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unlock and change password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_UnlockAndChangePassword {
            get {
                return ResourceManager.GetString("Settings_UnlockAndChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (not used) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongFilesItemContextMenu_Add {
            get {
                return ResourceManager.GetString("SongFilesItemContextMenu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongFilesListviewColumnHeader_File {
            get {
                return ResourceManager.GetString("SongFilesListviewColumnHeader_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongFilesListviewColumnHeader_Path {
            get {
                return ResourceManager.GetString("SongFilesListviewColumnHeader_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add to Queue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongsItemContextMenu_Add {
            get {
                return ResourceManager.GetString("SongsItemContextMenu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The MPD protocol version {0} is old. Some of the functionalities may not work properly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusBarMsg_MPDVersionIsOld {
            get {
                return ResourceManager.GetString("StatusBarMsg_MPDVersionIsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating database... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusMsg_UpdatingDb {
            get {
                return ResourceManager.GetString("StatusMsg_UpdatingDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TreeviewMenuItemContextMenu_Load {
            get {
                return ResourceManager.GetString("TreeviewMenuItemContextMenu_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Website に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
