//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPDCtrl.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPDCtrl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. (ConnectFail_Timeout) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_ConnectFail_Timeout {
            get {
                return ResourceManager.GetString("ConnectionStatus_ConnectFail_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_Connecting {
            get {
                return ResourceManager.GetString("ConnectionStatus_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionStatus_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to connect to specified MPD server. Please check your connection settings or MPD server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_ConnectionErrorDetails {
            get {
                return ResourceManager.GetString("ConnectionStatus_ConnectionErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_DisconnectedByHost {
            get {
                return ResourceManager.GetString("ConnectionStatus_DisconnectedByHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_DisconnectedByUser {
            get {
                return ResourceManager.GetString("ConnectionStatus_DisconnectedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_NeverConnected {
            get {
                return ResourceManager.GetString("ConnectionStatus_NeverConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. Reconnecting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_Reconnecting {
            get {
                return ResourceManager.GetString("ConnectionStatus_Reconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_SendFail_NotConnected {
            get {
                return ResourceManager.GetString("ConnectionStatus_SendFail_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_SendFail_Timeout {
            get {
                return ResourceManager.GetString("ConnectionStatus_SendFail_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Developer Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeveloperMode {
            get {
                return ResourceManager.GetString("DeveloperMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comfirmation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Comfirmation {
            get {
                return ResourceManager.GetString("Dialog_Comfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Information {
            get {
                return ResourceManager.GetString("Dialog_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Input {
            get {
                return ResourceManager.GetString("Dialog_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Playlist Name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_NewPlaylistName {
            get {
                return ResourceManager.GetString("Dialog_NewPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playlist name already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_PlaylistNameAlreadyExists {
            get {
                return ResourceManager.GetString("Dialog_PlaylistNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove selected playlist? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_RemovePlaylistQ {
            get {
                return ResourceManager.GetString("Dialog_RemovePlaylistQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Host に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copyright (c) 2020 torum
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permiss [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The MIT License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LicenseTitle {
            get {
                return ResourceManager.GetString("LicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocalfileItemContextMenu_Add {
            get {
                return ResourceManager.GetString("LocalfileItemContextMenu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Local Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocalfileListviewTabitemHeader_LocalFiles {
            get {
                return ResourceManager.GetString("LocalfileListviewTabitemHeader_LocalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MPD Command Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MPD_CommandError {
            get {
                return ResourceManager.GetString("MPD_CommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MPD Status Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MPD_StatusError {
            get {
                return ResourceManager.GetString("MPD_StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Optional に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_BackButton {
            get {
                return ResourceManager.GetString("Playback_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_NextButton {
            get {
                return ResourceManager.GetString("Playback_NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play/Pause に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_PlayPauseButton {
            get {
                return ResourceManager.GetString("Playback_PlayPauseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seek に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_SliderSeek {
            get {
                return ResourceManager.GetString("Playback_SliderSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_SliderVolume {
            get {
                return ResourceManager.GetString("Playback_SliderVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaybackOptions_Consume {
            get {
                return ResourceManager.GetString("PlaybackOptions_Consume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaybackOptions_Repeat {
            get {
                return ResourceManager.GetString("PlaybackOptions_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shuffle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaybackOptions_Shuffle {
            get {
                return ResourceManager.GetString("PlaybackOptions_Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear current queue and Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistItemContextMenu_ClearAndLoad {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_ClearAndLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistItemContextMenu_Load {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistItemContextMenu_Remove {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistItemContextMenu_Rename {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playlists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistListviewTabitemHeader_Playlists {
            get {
                return ResourceManager.GetString("PlaylistListviewTabitemHeader_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App Privacy Policy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MPDCtrl app allows you to access your music player via IP address and optionaly user credentials. None of this data is transmitted anywhere besides your specified music player and your settings are stored on your device only. Optional user credentials are encrypted with a platform provided shceme. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrivacyPolicyText {
            get {
                return ResourceManager.GetString("PrivacyPolicyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profiles に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid address format. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ErrorHostInvalidAddressFormat {
            get {
                return ResourceManager.GetString("Settings_ErrorHostInvalidAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Host address is required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ErrorHostMustBeSpecified {
            get {
                return ResourceManager.GetString("Settings_ErrorHostMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Port number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ErrorInvalidPortNaN {
            get {
                return ResourceManager.GetString("Settings_ErrorInvalidPortNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port number is required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ErrorPortMustBeSpecified {
            get {
                return ResourceManager.GetString("Settings_ErrorPortMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile Deleted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ProfileDeleted {
            get {
                return ResourceManager.GetString("Settings_ProfileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ProfileSaved {
            get {
                return ResourceManager.GetString("Settings_ProfileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile updated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ProfileUpdated {
            get {
                return ResourceManager.GetString("Settings_ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Debug Widow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowDebugWidow {
            get {
                return ResourceManager.GetString("ShowDebugWidow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Queue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongItemContextMenu_Queue {
            get {
                return ResourceManager.GetString("SongItemContextMenu_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongItemContextMenu_QueueClear {
            get {
                return ResourceManager.GetString("SongItemContextMenu_QueueClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongItemContextMenu_QueueSaveAsPlaylist {
            get {
                return ResourceManager.GetString("SongItemContextMenu_QueueSaveAsPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongItemContextMenu_Remove {
            get {
                return ResourceManager.GetString("SongItemContextMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Album に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongListViewColumnHeader_Album {
            get {
                return ResourceManager.GetString("SongListViewColumnHeader_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongListViewColumnHeader_Artist {
            get {
                return ResourceManager.GetString("SongListViewColumnHeader_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genre に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongListViewColumnHeader_Genre {
            get {
                return ResourceManager.GetString("SongListViewColumnHeader_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Song に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongListViewColumnHeader_Song {
            get {
                return ResourceManager.GetString("SongListViewColumnHeader_Song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongListViewColumnHeader_Time {
            get {
                return ResourceManager.GetString("SongListViewColumnHeader_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update MPD Music Database on Startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateDatabaseOnStartup {
            get {
                return ResourceManager.GetString("UpdateDatabaseOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Website に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
