//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPDCtrl.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPDCtrl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangePasswordDialog_ChangePassword {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangePasswordDialog_CurrentPassword {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Password did not match. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangePasswordDialog_CurrentPasswordMismatch {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_CurrentPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangePasswordDialog_NewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password Updated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangePasswordDialog_PasswordUpdated {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_Connected {
            get {
                return ResourceManager.GetString("ConnectionStatus_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. (ConnectFail_Timeout) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_ConnectFail_Timeout {
            get {
                return ResourceManager.GetString("ConnectionStatus_ConnectFail_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_Connecting {
            get {
                return ResourceManager.GetString("ConnectionStatus_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionStatus_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to connect to specified MPD server. Please check your connection settings or MPD server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_ConnectionErrorDetails {
            get {
                return ResourceManager.GetString("ConnectionStatus_ConnectionErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_DisconnectedByHost {
            get {
                return ResourceManager.GetString("ConnectionStatus_DisconnectedByHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_DisconnectedByUser {
            get {
                return ResourceManager.GetString("ConnectionStatus_DisconnectedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_NeverConnected {
            get {
                return ResourceManager.GetString("ConnectionStatus_NeverConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. Reconnecting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_Reconnecting {
            get {
                return ResourceManager.GetString("ConnectionStatus_Reconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_SendFail_NotConnected {
            get {
                return ResourceManager.GetString("ConnectionStatus_SendFail_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_SendFail_Timeout {
            get {
                return ResourceManager.GetString("ConnectionStatus_SendFail_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Developer Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeveloperMode {
            get {
                return ResourceManager.GetString("DeveloperMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close (Esc) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_CancelClose {
            get {
                return ResourceManager.GetString("Dialog_CancelClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comfirmation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Comfirmation {
            get {
                return ResourceManager.GetString("Dialog_Comfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Information {
            get {
                return ResourceManager.GetString("Dialog_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Input {
            get {
                return ResourceManager.GetString("Dialog_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Playlist Name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_NewPlaylistName {
            get {
                return ResourceManager.GetString("Dialog_NewPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playlist name already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_PlaylistNameAlreadyExists {
            get {
                return ResourceManager.GetString("Dialog_PlaylistNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_PlaylistSelect_NewPlaylistName {
            get {
                return ResourceManager.GetString("Dialog_PlaylistSelect_NewPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Selected to に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_PlaylistSelect_SaveSelectedTo {
            get {
                return ResourceManager.GetString("Dialog_PlaylistSelect_SaveSelectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_PlaylistSelect_SelectPlaylist {
            get {
                return ResourceManager.GetString("Dialog_PlaylistSelect_SelectPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove selected playlist? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_RemovePlaylistQ {
            get {
                return ResourceManager.GetString("Dialog_RemovePlaylistQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear Filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterClear {
            get {
                return ResourceManager.GetString("FilterClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Host に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Connection Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Init_NewConnectionSetting {
            get {
                return ResourceManager.GetString("Init_NewConnectionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copyright (c) 2020 torum
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permiss [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The MIT License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LicenseTitle {
            get {
                return ResourceManager.GetString("LicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add (Enter) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocalfileItemContextMenu_Add {
            get {
                return ResourceManager.GetString("LocalfileItemContextMenu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocalfileListviewColumnHeader_FileName {
            get {
                return ResourceManager.GetString("LocalfileListviewColumnHeader_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocalfileListviewTabitemHeader_LocalFiles {
            get {
                return ResourceManager.GetString("LocalfileListviewTabitemHeader_LocalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MPD Command Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MPD_CommandError {
            get {
                return ResourceManager.GetString("MPD_CommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MPD Status Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MPD_StatusError {
            get {
                return ResourceManager.GetString("MPD_StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_BackButton {
            get {
                return ResourceManager.GetString("Playback_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_NextButton {
            get {
                return ResourceManager.GetString("Playback_NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play/Pause に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_PlayPauseButton {
            get {
                return ResourceManager.GetString("Playback_PlayPauseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seek に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_SliderSeek {
            get {
                return ResourceManager.GetString("Playback_SliderSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_SliderVolume {
            get {
                return ResourceManager.GetString("Playback_SliderVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaybackOptions_Consume {
            get {
                return ResourceManager.GetString("PlaybackOptions_Consume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaybackOptions_Repeat {
            get {
                return ResourceManager.GetString("PlaybackOptions_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shuffle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaybackOptions_Shuffle {
            get {
                return ResourceManager.GetString("PlaybackOptions_Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear current queue and Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistItemContextMenu_ClearAndLoad {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_ClearAndLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load (Enter) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistItemContextMenu_Load {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistItemContextMenu_Remove {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistItemContextMenu_Rename {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Playlists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistListviewTabitemHeader_Playlists {
            get {
                return ResourceManager.GetString("PlaylistListviewTabitemHeader_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App Privacy Policy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MPDCtrl app allows you to access your music player via IP address and optionaly user credentials. None of this data is transmitted anywhere besides your specified music player and your settings are stored on your device only. Optional user credentials are encrypted with a platform provided shceme. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrivacyPolicyText {
            get {
                return ResourceManager.GetString("PrivacyPolicyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profiles に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_Move {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Down (CTRL+D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_MoveDown {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Up (CTRL+U) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_MoveUp {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Queue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_Queue {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_QueueClear {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_QueueClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_QueueSaveAsPlaylist {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_QueueSaveAsPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove (CTRL+Delete) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_Remove {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save to に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_SaveToPlaylist {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_SaveToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected Items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueItemContextMenu_SelectedItems {
            get {
                return ResourceManager.GetString("QueueItemContextMenu_SelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Album に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueListviewColumnHeader_Album {
            get {
                return ResourceManager.GetString("QueueListviewColumnHeader_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueListviewColumnHeader_Artist {
            get {
                return ResourceManager.GetString("QueueListviewColumnHeader_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genre に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueListviewColumnHeader_Genre {
            get {
                return ResourceManager.GetString("QueueListviewColumnHeader_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last Modified に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueListviewColumnHeader_LastModified {
            get {
                return ResourceManager.GetString("QueueListviewColumnHeader_LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueListviewColumnHeader_Position {
            get {
                return ResourceManager.GetString("QueueListviewColumnHeader_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueListviewColumnHeader_Time {
            get {
                return ResourceManager.GetString("QueueListviewColumnHeader_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueueListviewColumnHeader_Title {
            get {
                return ResourceManager.GetString("QueueListviewColumnHeader_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search (Ctrl+F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search_ToolTip {
            get {
                return ResourceManager.GetString("Search_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid address format. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ErrorHostInvalidAddressFormat {
            get {
                return ResourceManager.GetString("Settings_ErrorHostInvalidAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Host address is required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ErrorHostMustBeSpecified {
            get {
                return ResourceManager.GetString("Settings_ErrorHostMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Port number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ErrorInvalidPortNaN {
            get {
                return ResourceManager.GetString("Settings_ErrorInvalidPortNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port number is required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ErrorPortMustBeSpecified {
            get {
                return ResourceManager.GetString("Settings_ErrorPortMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Debug Widow (this may significantly slow down repoponsiveness) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_ShowDebugWidow {
            get {
                return ResourceManager.GetString("Settings_Opts_ShowDebugWidow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update MPD Music Database on Startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_UpdateDatabaseOnStartup {
            get {
                return ResourceManager.GetString("Settings_Opts_UpdateDatabaseOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile Deleted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ProfileDeleted {
            get {
                return ResourceManager.GetString("Settings_ProfileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile Saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ProfileSaved {
            get {
                return ResourceManager.GetString("Settings_ProfileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile Updated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ProfileUpdated {
            get {
                return ResourceManager.GetString("Settings_ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings (Ctrl+S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ToolTip {
            get {
                return ResourceManager.GetString("Settings_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unlock and Change Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_UnlockAndChangePassword {
            get {
                return ResourceManager.GetString("Settings_UnlockAndChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add to Current Queue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongFilesItemContextMenu_Add {
            get {
                return ResourceManager.GetString("SongFilesItemContextMenu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongFilesListviewColumnHeader_File {
            get {
                return ResourceManager.GetString("SongFilesListviewColumnHeader_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongFilesListviewColumnHeader_Path {
            get {
                return ResourceManager.GetString("SongFilesListviewColumnHeader_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add to Current Queue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongsItemContextMenu_Add {
            get {
                return ResourceManager.GetString("SongsItemContextMenu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating db... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusMsg_UpdatingDb {
            get {
                return ResourceManager.GetString("StatusMsg_UpdatingDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Website に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
